name: Check and Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  check:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Prepare mkvtoolnix
        run: |
          sudo wget -O /usr/share/keyrings/gpg-pub-moritzbunkus.gpg https://mkvtoolnix.download/gpg-pub-moritzbunkus.gpg
          echo "deb [signed-by=/usr/share/keyrings/gpg-pub-moritzbunkus.gpg] https://mkvtoolnix.download/ubuntu/ jammy main" | sudo tee -a /etc/apt/sources.list.d/mkvtoolnix.download.list
          echo "deb-src [signed-by=/usr/share/keyrings/gpg-pub-moritzbunkus.gpg] https://mkvtoolnix.download/ubuntu/ jammy main" | sudo tee -a /etc/apt/sources.list.d/mkvtoolnix.download.list
          sudo apt update
          sudo apt install mkvtoolnix

      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: requirements.txt  # this is optional

      # the package installation will only be executed when the
      # requirements-files have changed.
      - name: Install dependencies
        run: pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        
      - name: Run Episode
        run: |
          for i in {1..1}; do
            python3 main.py $i
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: subtitles-build
          path: |
            final/*.mks
            final/*.ass

  build:
    runs-on: ubuntu-22.04
    needs: check
    if: "contains(github.event.head_commit.message, '[build]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: subtitles-build
          path: |
            final/*.mks
            final/*.ass

      - name: List files
        run: |
          ls -alh
          ls -alh final

      - name: Write files
        run: |
          echo "*.mks filter=lfs diff=lfs merge=lfs -text" >> final/.gitattributes
          cat <<EOT >> ./final/README.md
          # [‽] Bocchi sang Roker! - Subtitle File
          Silakan unduh file `*.mks` dan mux ke video favorit anda!<br />
          Atau, silakan download file takarir diatas, lalu mux dengan video anda dan unduh font dari branch `master`.<br />
          EOT

      - name: Deploy to Archive
        uses: s0/git-publish-subdir-action@develop
        env:
          BRANCH: subtitles
          REPO: self
          FOLDER: final
          GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
          MESSAGE: "📈 Perubahan takarir @ n4o-fansub/Bocchi-sang-Roker@{long-sha}"